export const Ideas = `{
  "template": ["A {disabilities} {Genre} game featuring a {abilities} {Entity} that has to {Objective}"],
  "gameMood": [
    "peaceful",
    "melancholic", 
    "challenging", 
    "black and white", 
    "monochrome"
  ],
  "disabilities": [
    "no jump",
    "save state is a currency",
    "only 2 button" 
  ],
  "abilities": [
    "levitating",
    "heavy",
    "huge" 
  ],
  "Adjective": [
    "old",
    "slimey",
    "crooked",
    "furry",
    "dark",
    "metal",
    "muddy",
    "sleepy",
    "lazy"
  ],
  "role": [
    "fisherman",
    "miner",
    "fireman",
    "scout",
    "actor",
    "farmer",
    "king",
    "photographer",
    "pilot",
    "investigator",
    "mafioso",
    "policeman",
    "chef"
  ],
  "verb": ["singing", "yelling", "dancing", "digging", "farming", "killing"],
  "tool": [
    "shovel(s)",
    "spoon(s)",
    "kite(s)",
    "fishing rod(s)",
    "leaf(s)",
    "violin(s)",
    "flashlight(s)",
    "candle(s)",
    "hook(s)",
    "skateboard(s)",
    "seashell(s)",
    "balloon(s)"
  ],
  "Entity": [
    "zombie(s)",
    "frog(s)",
    "cat(s)",
    "sword fish",
    "slime(s)",
    "seagull(s)",
    "bird(s)",
    "snake(s)",
    "racoon(s)",
    "knight(s)",
    "sea monster(s)",
    "spider(s)",
    "scarecrow(s)",
    "platypus(es)",
    "butterfly(es)",
    "ocean diver(s)",
    "squirrel(s)",
    "bear(s)"
  ],
  "Objective": [
    "who saves {EntityS} in aid of a {tool}",
    "save {EntityS} from a {Adjective} {Entity}",
    "kill all {EntityS} with his {tool}",
    "sell {EntityS}",
    "sell {toolS} to {EntityS}",
    "collect {toolS}",
    "defeat an evil {Entity}",
    "farm {EntityS}",
    "distribute {toolS} to {EntityS}",
    "help {EntityS} {Objective}",
    "prevent {EntityS} from {verb} in the {place}",
    "investigate the crimes of the {Entity} {role}",
    "clean the {place} to {Objective}",
    "{Objective} to {Objective}"
  ],
  "place": ["graveyard", "castle", "village", "ocean", "woods"],
  "Genre": [
    "survival",
    "sim",
    "management",
    "platforming",
    "card",
    "resource management",
    "strategy",
    "racing",
    "twin-stick shooter",
    "stealth",
    "survival horror",
    "roguelike",
    "collectathon",
    "arcade",
    "turn-based"
  ]
}`;
